---
- name: Restart ssh
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts.os_family == 'Debian' else 'sshd' }}"
    state: restarted
  failed_when: false

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  failed_when: false

